// ############################################################
// All listed setting can be changed only by editing this file
// Other settings can be changed from CPanel/Manage server
// ############################################################

var gsValues = new Array(); // do not remove

// map min zoom
gsValues['map_min_zoom'] = 3;

// map max zoom
gsValues['map_max_zoom'] = 18;

// realtime object data refresh, default 10 seconds
gsValues['map_refresh'] = 10;

// events refresh, default 30 seconds
gsValues['event_refresh'] = 30;

// cmd status refresh, default 60 seconds
gsValues['cmd_status_refresh'] = 60;

// img gallery refresh, default 60 seconds
gsValues['img_refresh'] = 60;

// chat refresh, default 10 seconds
gsValues['chat_refresh'] = 10;

// billing refresh, default 60 seconds
gsValues['billing_refresh'] = 60;

// check if user session is still active if not block and ask for login, default 30 seconds, false - do not check;
gsValues['session_check'] = 30;

// default object control commands
gsValues['cmd_default'] = new Array();
gsValues['cmd_default'] = [
                                {name: 'alarm_arm'},
                                {name: 'alarm_disarm'},
                                {name: 'command_interval', params: '120'},
                                {name: 'engine_resume'},
                                {name: 'engine_stop'},
                                {name: 'output_off', params: '1'},
                                {name: 'output_on', params: '1'},
                                {name: 'photo_request'},
                                {name: 'position_interval', params: '60'},                               
                                {name: 'tracking_start'},
                                {name: 'tracking_stop'}                                
                          ];
                                
// supported GPS device protocols
gsValues['protocol_list'] = new Array();
gsValues['protocol_list'] = [
                                {name: 'android', cmd: 'tracking_start,tracking_stop,position_interval,command_interval'},
                                {name: 'iphone', cmd: 'tracking_start,tracking_stop,position_interval,command_interval'},
                                {name: 'demo'},
                                {name: 'agps'},
                                {name: 'amit'},
                                {name: 'amt'},
                                {name: 'amwell', cmd: 'engine_resume,engine_stop'},
                                {name: 'anbtek'},
                                {name: 'apkcom'},
                                {name: 'aplicom'},
                                {name: 'aquilatrack'},
                                {name: 'atrack'},
                                {name: 'autofon'},
                                {name: 'autoleaders'},
                                {name: 'bce'},
                                {name: 'benway', cmd: 'engine_resume,engine_stop'},
                                {name: 'bitrek'},
                                {name: 'bofan', cmd: 'output_off,output_on,photo_request'},
                                {name: 'boxtelematics'},
                                {name: 'bstechnotronics'},
                                {name: 'c2stek'},
                                {name: 'calamp'},
                                {name: 'cantrack'},
                                {name: 'careuueco'},
                                {name: 'carrideo'},
                                {name: 'castelobd'},
                                {name: 'castelsat802'},
                                {name: 'chinaradio'},
                                {name: 'coban', cmd: 'alarm_arm,alarm_disarm,engine_resume,engine_stop,position_interval'},
                                {name: 'cobangmt'},                                
                                {name: 'concoxgb100'},
                                {name: 'concoxgt02'},
                                {name: 'concoxgt03'},
                                {name: 'concoxgt06', cmd: 'engine_resume,engine_stop'},
                                {name: 'concoxgt100'},
                                {name: 'concoxgt300', cmd: 'engine_resume,engine_stop'},
                                {name: 'concoxgt710', cmd: 'engine_resume,engine_stop'},
                                {name: 'concoxgt800', cmd: 'engine_resume,engine_stop'},
                                {name: 'concoxjc100', cmd: 'engine_resume,engine_stop'},
                                {name: 'concoxx1', cmd: 'engine_resume,engine_stop'},
                                {name: 'cybergraphy'},
                                {name: 'dct'},
                                {name: 'detero'},
                                {name: 'digitalsystemsdsf'},
                                {name: 'digitalsystemsdsf30'},
                                {name: 'disha'},
                                {name: 'eelink'},
                                {name: 'eniac'},
                                {name: 'falcomsteppiii'},
                                {name: 'falcomsteppiii_wo_gpiop'},
                                {name: 'fifotrack', cmd: 'engine_resume,engine_stop,photo_request'},
                                {name: 'flextrack'},
                                {name: 'galileosky'},
                                {name: 'gator'},
                                {name: 'genekofox'},
                                {name: 'globalsattr151'},
                                {name: 'globalsattr203'},
                                {name: 'globalsattr600'},
                                {name: 'globalsattr606'},
                                {name: 'globalsatgtr128'},
                                {name: 'gopass'},
                                {name: 'gosafe'},
                                {name: 'gosafeg1c'},
                                {name: 'gotop'},
                                {name: 'haicom'},
                                {name: 'hbt10'},
                                {name: 'inteliot'},
                                {name: 'intellitracx1'},
                                {name: 'internex'},
                                {name: 'istartekvt206'},
                                {name: 'istartekvt600'},
                                {name: 'itrac'},
                                {name: 'itraca1'},
                                {name: 'jointech'},
                                {name: 'jointechjt701'},
                                {name: 'jtrack'},
                                {name: 'keson'},
                                {name: 'khd'},
                                {name: 'khm100a'},
                                {name: 'lkgps'},
                                {name: 'maestro'},
                                {name: 'mastrack'},
                                {name: 'maxepor'},
                                {name: 'megastek'},
                                {name: 'megastekgvt369'},
                                {name: 'megastekgvt800'},
                                {name: 'meiligao'},
                                {name: 'meitrack', cmd: 'alarm_arm,alarm_disarm,engine_resume,engine_stop'},
                                {name: 'meitrackp99g'},
                                {name: 'meitrackt322'},
                                {name: 'mictrack'},
                                {name: 'minifinder'},
                                {name: 'minova'},
                                {name: 'mplatam100'},
                                {name: 'mplatam15'},
                                {name: 'mplatat150'},
                                {name: 'navtelecom'},
                                {name: 'neomatica'},
                                {name: 'noran'},
                                {name: 'oigo'},
                                {name: 'oko'},
                                {name: 'oner'},
                                {name: 'oriontechnology'},
                                {name: 'pftechnologies'},
                                {name: 'pointer', cmd: 'output_off,output_on'},
                                {name: 'pretrace'},
                                {name: 'qbit'},
                                {name: 'queclink'},
                                {name: 'queclinkgb100'},
                                {name: 'queclinkgl200'},
                                {name: 'queclinkgl300'},
                                {name: 'queclinkgl300w'},
                                {name: 'queclinkgl500'},
                                {name: 'queclinkgmt100'},
                                {name: 'queclinkgmt200'},
                                {name: 'queclinkgs100'},
                                {name: 'queclinkgt300'},
                                {name: 'queclinkgt301'},
                                {name: 'queclinkgt500'},
                                {name: 'queclinkgv200'},
                                {name: 'queclinkgv300'},
                                {name: 'queclinkgv300w'},
                                {name: 'queclinkgv500'},
                                {name: 'queclinkgv55'},
                                {name: 'queclinkgv65'},
                                {name: 'queclinkgv75'},
                                {name: 'queclinkgv75w'},
                                {name: 'queclinktrs'},
                                {name: 'raveon'},
                                {name: 'roadsay'},
                                {name: 'ruptela'},
                                {name: 'sanav'},
                                {name: 'satellitesolutions'},
                                {name: 'silicontechlabs'},
                                {name: 'siwi'},
                                {name: 'skypatrol'},
                                {name: 'skytrackjb101'},
                                {name: 'speedotrack'},
                                {name: 'spystoreitaliaperfect3'},
                                {name: 'starcom'},
                                {name: 'suntech'},
                                {name: 'suntechst200'},
                                {name: 'suntechst300'},
                                {name: 'suntechst500'},
                                {name: 'suntechst600'},
                                {name: 'suntechst910'},
                                {name: 'telcomip'},
                                {name: 'telic'},
                                {name: 'teltonikaat'},
                                {name: 'teltonikafm'},
                                {name: 'teltonikagh'},
                                {name: 'thinkpower'},
                                {name: 'tkstar'},
                                {name: 'tkstartk905'},
                                {name: 'tlt2h'},
                                {name: 'topflytech', cmd: 'engine_resume,engine_stop'},
                                {name: 'topin'},
                                {name: 'topten', cmd: 'photo_request'},
                                {name: 'totemtech'},
                                {name: 'tracerx2'},
                                {name: 'trackpro'},
                                {name: 'tramigo'},
                                {name: 'twig'},
                                {name: 'trackertechnologymsp340'},
                                {name: 'trackertechnologymsp350'},
                                {name: 'tytan'},
                                {name: 'tzonedigital'},
                                {name: 'ulbotech'},
                                {name: 'uniguard'},
                                {name: 'unknown056'},
                                {name: 'unknown807rf'},
                                {name: 'unknowncctr800'},
                                {name: 'unknowng64'},
                                {name: 'unknowngm908'},
                                {name: 'unknowngp106m'},
                                {name: 'unknowngpst1086'},
                                {name: 'unknownhw18'},
                                {name: 'unknownm60'},
                                {name: 'unknownpg88'},
                                {name: 'unknownpolgps1'},
                                {name: 'unknownpt3000'},
                                {name: 'unknownstl060'},
                                {name: 'unknownt0024'},
                                {name: 'unknowntc45'},
                                {name: 'unknowntk103'},
                                {name: 'unknowntk103_2'},
                                {name: 'unknowntk103_3'},
                                {name: 'unknowntk103_4'},
                                {name: 'unknowntk103_5'},
                                {name: 'unknowntk106'},
                                {name: 'unknowntk20g'},
                                {name: 'unknowntl206'},
                                {name: 'unknowntr10'},
                                {name: 'unknownvt206'},
                                {name: 'unknownwb1g'},
                                {name: 'vgmatics'},
                                {name: 'visiontek86vtu'},
                                {name: 'visiontek87vtu'},
                                {name: 'carrideo'},
                                {name: 'wialonips'},
                                {name: 'xexun'},
                                {name: 'yuwei'},
                                {name: 'zendazdvt2'}
                        ];